[build]
  publish = "build/web"
  command = "if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release"

[build.environment]
  FLUTTER_VERSION = "3.29.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
